### ISSUE TITLE
As a customer, I want to consult the products available for sale.

### ISSUE THREAD

**Issue by anaines14** [FEUP-ESOF-2020-21/open-cx-t1g3-pantufas#1]
https://github.com/FEUP-ESOF-2020-21/open-cx-t1g3-pantufas#user-story-1

**Comment by JoaoCostaIFG** [comment]
It's about time to close this issue for now.
We all worked on this one because we didn't understand flutter.

**Comment by JoaoCostaIFG** [comment]
Reopening issue to syncronize with avion.

**Comment by JoaoCostaIFG** [comment]
Avion import is done.
