### ISSUE TITLE
Migrate JSON to Firebase

### ISSUE THREAD

**Issue by rfontao** [FEUP-ESOF-2020-21/open-cx-t1g3-pantufas#2]
Migrate from JSON (see #1) to firebase .

**Comment by rfontao** [comment]
Migration to Firebase was implemented and merged into the [development branch](/FEUP-ESOF-2020-21/open-cx-t1g3-pantufas/tree/development).

**Comment by JoaoCostaIFG** [comment]
Reopening issue to syncronize with avion.

**Comment by JoaoCostaIFG** [comment]
Avion import is done.
