### ISSUE TITLE
As a customer, I want to be able to order food/drinks from the available products.

### ISSUE THREAD

**Issue by JoaoCostaIFG** [FEUP-ESOF-2020-21/open-cx-t1g3-pantufas#3]
https://github.com/FEUP-ESOF-2020-21/open-cx-t1g3-pantufas#user-story-3

**Comment by JoaoCostaIFG** [comment]
Most work is being done in [this branch](/FEUP-ESOF-2020-21/open-cx-t1g3-pantufas/tree/cart).

When issue #4 is done, we cans start saving cart contents on firebase.

**Comment by JoaoCostaIFG** [comment]
[Cart branch](https://github.com/FEUP-ESOF-2020-21/open-cx-t1g3-pantufas/tree/cart) has been merged to development. Currently, it is only missing real checkout capabilities (not going to be implmented).

@joaolucasmartins Close this issues if you have nothing else to add.

**Comment by joaolucasmartins** [comment]
The code has been merged to the development branch.

**Comment by JoaoCostaIFG** [comment]
Reopening issue to syncronize with avion.

**Comment by JoaoCostaIFG** [comment]
Avion import is done.
