### ISSUE TITLE
As a customer, I must log in into my account to place orders.

### ISSUE THREAD

**Issue by JoaoCostaIFG** [FEUP-ESOF-2020-21/open-cx-t1g3-pantufas#4]
https://github.com/FEUP-ESOF-2020-21/open-cx-t1g3-pantufas#user-story-2

**Comment by JoaoCostaIFG** [comment]
See related issue: #2.

**Comment by rfontao** [comment]
Closed in development branch. @JoaoCostaIFG

**Comment by JoaoCostaIFG** [comment]
oki doki

**Comment by JoaoCostaIFG** [comment]
Reopening issue to syncronize with avion.

**Comment by JoaoCostaIFG** [comment]
Avion import is done.
