### ISSUE TITLE
Reorganize login/register/cart appearance (AppBar)

### ISSUE THREAD

**Issue by JoaoCostaIFG** [FEUP-ESOF-2020-21/open-cx-t1g3-pantufas#7]
With the addition of log-in/register capabilites and the cart icon, we have a need for a constant look to the AppBar transversal to the whole application.

**Comment by JoaoCostaIFG** [comment]
See issues: #3 and #4.

**Comment by anaines14** [comment]
Issue code has been merged to development branch.

**Comment by JoaoCostaIFG** [comment]
Reopening issue to syncronize with avion.

**Comment by JoaoCostaIFG** [comment]
Reopening issue to syncronize with avion.

**Comment by JoaoCostaIFG** [comment]
Avion import is done.
