### ISSUE TITLE
Helper class for AppBar and global state related functions.

### ISSUE THREAD

**Issue by JoaoCostaIFG** [FEUP-ESOF-2020-21/open-cx-t1g3-pantufas#8]
A class that can generate the AppBar and have heelper funcionts that can/could be used everywhere (e.g.: navigatorPopAll).

**Comment by rfontao** [comment]
Closed with #23

**Comment by JoaoCostaIFG** [comment]
Reopening issue to syncronize with avion.

**Comment by JoaoCostaIFG** [comment]
Avion import is done.
